/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

/**
 *
 * @author mc7355u
 */
public class mapLondon extends javax.swing.JFrame {

    String boroughLondon="";
    /**
     * Creates new form mapLondon
     */
    AddJourneyForm first;
    public mapLondon(AddJourneyForm f) {
        initComponents();
        first = f;
    }
    
    /*public String getSelectedBorough(){
        return boroughLondon;
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Havering = new javax.swing.JLabel();
        Barking = new javax.swing.JLabel();
        Redbridge = new javax.swing.JLabel();
        Waltham = new javax.swing.JLabel();
        Einfield = new javax.swing.JLabel();
        Barnet = new javax.swing.JLabel();
        Haringey = new javax.swing.JLabel();
        Harrow = new javax.swing.JLabel();
        Hillingdon = new javax.swing.JLabel();
        Brent = new javax.swing.JLabel();
        Ealing = new javax.swing.JLabel();
        Hounslow = new javax.swing.JLabel();
        RichmondUponTimes = new javax.swing.JLabel();
        Wandsworth = new javax.swing.JLabel();
        Merton = new javax.swing.JLabel();
        Sutton = new javax.swing.JLabel();
        KingstonUponThames = new javax.swing.JLabel();
        Bromley = new javax.swing.JLabel();
        Croydon = new javax.swing.JLabel();
        Bexley = new javax.swing.JLabel();
        Southwark = new javax.swing.JLabel();
        Lewisham = new javax.swing.JLabel();
        Greenwich = new javax.swing.JLabel();
        Lambeth = new javax.swing.JLabel();
        KensingtonChelsea = new javax.swing.JLabel();
        Westminster = new javax.swing.JLabel();
        Newham = new javax.swing.JLabel();
        Camden = new javax.swing.JLabel();
        HammersmithFulham = new javax.swing.JLabel();
        Islington = new javax.swing.JLabel();
        Hackney = new javax.swing.JLabel();
        theCity = new javax.swing.JLabel();
        TowerHamlets = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Havering.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Havering.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HaveringMouseClicked(evt);
            }
        });

        Barking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Barking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarkingMouseClicked(evt);
            }
        });

        Redbridge.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Redbridge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RedbridgeMouseClicked(evt);
            }
        });

        Waltham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Waltham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WalthamMouseClicked(evt);
            }
        });

        Einfield.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Einfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EinfieldMouseClicked(evt);
            }
        });

        Barnet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Barnet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarnetMouseClicked(evt);
            }
        });

        Haringey.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Haringey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HaringeyMouseClicked(evt);
            }
        });

        Harrow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Harrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HarrowMouseClicked(evt);
            }
        });

        Hillingdon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hillingdon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HillingdonMouseClicked(evt);
            }
        });

        Brent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Brent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BrentMouseClicked(evt);
            }
        });

        Ealing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ealing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EalingMouseClicked(evt);
            }
        });

        Hounslow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hounslow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HounslowMouseClicked(evt);
            }
        });

        RichmondUponTimes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RichmondUponTimes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RichmondUponTimesMouseClicked(evt);
            }
        });

        Wandsworth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Wandsworth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WandsworthMouseClicked(evt);
            }
        });

        Merton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Merton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MertonMouseClicked(evt);
            }
        });

        Sutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SuttonMouseClicked(evt);
            }
        });

        KingstonUponThames.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KingstonUponThames.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KingstonUponThamesMouseClicked(evt);
            }
        });

        Bromley.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bromley.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BromleyMouseClicked(evt);
            }
        });

        Croydon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Croydon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CroydonMouseClicked(evt);
            }
        });

        Bexley.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bexley.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BexleyMouseClicked(evt);
            }
        });

        Southwark.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Southwark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SouthwarkMouseClicked(evt);
            }
        });

        Greenwich.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Greenwich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GreenwichMouseClicked(evt);
            }
        });

        Lambeth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lambeth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LambethMouseClicked(evt);
            }
        });

        KensingtonChelsea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KensingtonChelsea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KensingtonChelseaMouseClicked(evt);
            }
        });

        Westminster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Westminster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WestminsterMouseClicked(evt);
            }
        });

        Newham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Newham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewhamMouseClicked(evt);
            }
        });

        Camden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Camden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CamdenMouseClicked(evt);
            }
        });

        HammersmithFulham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HammersmithFulham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HammersmithFulhamMouseClicked(evt);
            }
        });

        Islington.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Islington.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IslingtonMouseClicked(evt);
            }
        });

        Hackney.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hackney.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HackneyMouseClicked(evt);
            }
        });

        theCity.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        theCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                theCityMouseClicked(evt);
            }
        });

        TowerHamlets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TowerHamlets.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                TowerHamletsAncestorRemoved(evt);
            }
        });
        TowerHamlets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TowerHamletsMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Secure/gcabsimages/LondonBoroughs.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(Einfield, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(Barnet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hounslow, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(RichmondUponTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(HammersmithFulham, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(KensingtonChelsea, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Lambeth, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Southwark, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Lewisham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(KingstonUponThames)
                .addGap(50, 50, 50)
                .addComponent(Merton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Croydon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Bromley, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(Sutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(Bexley, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(TowerHamlets, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(Wandsworth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(Greenwich, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(theCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(Havering, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Ealing, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(Westminster, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Hillingdon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Harrow, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Brent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Camden, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(Barking, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Haringey, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(Islington, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Waltham, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(Hackney, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(Newham, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(Redbridge, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Einfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Barnet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(Hillingdon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Harrow, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Brent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Haringey, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Islington, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Hackney, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Newham, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Hounslow, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(RichmondUponTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(HammersmithFulham, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KensingtonChelsea, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Lambeth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Southwark, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Lewisham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(KingstonUponThames, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Merton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Croydon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Bromley, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(Barking, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(Redbridge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(Bexley, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(Waltham, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(TowerHamlets, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(Greenwich, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(theCity, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(Havering, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(Ealing, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(Camden, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(Sutton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(Wandsworth, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Westminster, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HaveringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HaveringMouseClicked
        first.getData[0]="Havering";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_HaveringMouseClicked

    private void GreenwichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreenwichMouseClicked
        first.getData[0]="Greenwich";
        first.posData();
        this.setVisible(false);
        //boroughLondon="Greenwich";
        //System.out.println(boroughLondon);
    }//GEN-LAST:event_GreenwichMouseClicked

    private void BexleyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BexleyMouseClicked
        first.getData[0]="Bexley";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_BexleyMouseClicked

    private void BrentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrentMouseClicked
       first.getData[0]="Brent";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_BrentMouseClicked

    private void TowerHamletsAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TowerHamletsAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TowerHamletsAncestorRemoved

    private void TowerHamletsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TowerHamletsMouseClicked
        first.getData[0]="Tower Hamlets";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_TowerHamletsMouseClicked

    private void theCityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_theCityMouseClicked
        first.getData[0]="The City";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_theCityMouseClicked

    private void HackneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HackneyMouseClicked
        first.getData[0]="Hackney";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_HackneyMouseClicked

    private void IslingtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IslingtonMouseClicked
        first.getData[0]="Islington";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_IslingtonMouseClicked

    private void HammersmithFulhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HammersmithFulhamMouseClicked
        first.getData[0]="Hammersmith and Fulham";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_HammersmithFulhamMouseClicked

    private void CamdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CamdenMouseClicked
        first.getData[0]="Camden";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_CamdenMouseClicked

    private void NewhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewhamMouseClicked
        first.getData[0]="Newham";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_NewhamMouseClicked

    private void WestminsterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WestminsterMouseClicked
        first.getData[0]="Westminster";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_WestminsterMouseClicked

    private void KensingtonChelseaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KensingtonChelseaMouseClicked
        first.getData[0]="Kensington and Chelsea";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_KensingtonChelseaMouseClicked

    private void LambethMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LambethMouseClicked
        first.getData[0]="Lambeth";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_LambethMouseClicked

    private void SouthwarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SouthwarkMouseClicked
        first.getData[0]="Southwark";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_SouthwarkMouseClicked

    private void CroydonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CroydonMouseClicked
        first.getData[0]="Croydon";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_CroydonMouseClicked

    private void BromleyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BromleyMouseClicked
        first.getData[0]="Bromley";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_BromleyMouseClicked

    private void KingstonUponThamesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KingstonUponThamesMouseClicked
        first.getData[0]="Kingston Upon Thames";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_KingstonUponThamesMouseClicked

    private void SuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuttonMouseClicked
        first.getData[0]="Sutton";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_SuttonMouseClicked

    private void MertonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MertonMouseClicked
        first.getData[0]="Merton";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_MertonMouseClicked

    private void WandsworthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WandsworthMouseClicked
        first.getData[0]="Wandsworth";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_WandsworthMouseClicked

    private void RichmondUponTimesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RichmondUponTimesMouseClicked
        first.getData[0]="Richmond Upon Thames";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_RichmondUponTimesMouseClicked

    private void HounslowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HounslowMouseClicked
       first.getData[0]="Hounslow";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_HounslowMouseClicked

    private void EalingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EalingMouseClicked
        first.getData[0]="Ealing";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_EalingMouseClicked

    private void HillingdonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HillingdonMouseClicked
        first.getData[0]="Hillingdon";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_HillingdonMouseClicked

    private void HarrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HarrowMouseClicked
        first.getData[0]="Harrow";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_HarrowMouseClicked

    private void HaringeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HaringeyMouseClicked
        first.getData[0]="Haringey";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_HaringeyMouseClicked

    private void BarnetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarnetMouseClicked
        first.getData[0]="Barnet";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_BarnetMouseClicked

    private void EinfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EinfieldMouseClicked
        first.getData[0]="Einfield";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_EinfieldMouseClicked

    private void WalthamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WalthamMouseClicked
        first.getData[0]="Waltham forest";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_WalthamMouseClicked

    private void RedbridgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RedbridgeMouseClicked
       first.getData[0]="Redbridge";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_RedbridgeMouseClicked

    private void BarkingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarkingMouseClicked
        first.getData[0]="Barking and Dagenham";
        first.posData();
        this.setVisible(false);
    }//GEN-LAST:event_BarkingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mapLondon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mapLondon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mapLondon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mapLondon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new mapLondon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barking;
    private javax.swing.JLabel Barnet;
    private javax.swing.JLabel Bexley;
    private javax.swing.JLabel Brent;
    private javax.swing.JLabel Bromley;
    private javax.swing.JLabel Camden;
    private javax.swing.JLabel Croydon;
    private javax.swing.JLabel Ealing;
    private javax.swing.JLabel Einfield;
    private javax.swing.JLabel Greenwich;
    private javax.swing.JLabel Hackney;
    private javax.swing.JLabel HammersmithFulham;
    private javax.swing.JLabel Haringey;
    private javax.swing.JLabel Harrow;
    private javax.swing.JLabel Havering;
    private javax.swing.JLabel Hillingdon;
    private javax.swing.JLabel Hounslow;
    private javax.swing.JLabel Islington;
    private javax.swing.JLabel KensingtonChelsea;
    private javax.swing.JLabel KingstonUponThames;
    private javax.swing.JLabel Lambeth;
    private javax.swing.JLabel Lewisham;
    private javax.swing.JLabel Merton;
    private javax.swing.JLabel Newham;
    private javax.swing.JLabel Redbridge;
    private javax.swing.JLabel RichmondUponTimes;
    private javax.swing.JLabel Southwark;
    private javax.swing.JLabel Sutton;
    private javax.swing.JLabel TowerHamlets;
    private javax.swing.JLabel Waltham;
    private javax.swing.JLabel Wandsworth;
    private javax.swing.JLabel Westminster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel theCity;
    // End of variables declaration//GEN-END:variables
}
